# NUMPY

In [4]:
import numpy as np # np is the nickname for numpy


In [5]:
#numpy is like an array of number
a=np.array([1,2,3])
print(type(a), a.shape, a[1])
a[0]=10# reading or wrinting
print(a)

<class 'numpy.ndarray'> (3,) 2
[10  2  3]


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape) #row and column
print(b[0,0], b[1,2]) #print certain number

[[1 2 3]
 [4 5 6]]
(2, 3)
1 6


In [7]:
n1=np.zeros((2,2))
print(n1)

[[0. 0.]
 [0. 0.]]


In [8]:
n2=np.ones((1,2))
print(n2)


[[1. 1.]]


In [9]:
n3=np.full((2,2),7)
print(n3)


[[7 7]
 [7 7]]


In [10]:
n4=np.eye(2)
print(n4)

[[1. 0.]
 [0. 1.]]


In [11]:
import numpy as np
num4=np.random.random((2,2))
print(num4)

[[0.36969679 0.52405517]
 [0.92951152 0.5803736 ]]


In [12]:
any_var=b[1,:2]
print(any_var)

[4 5]
