In [2]:
import numpy as np

1. Create a numpy array of size 2 x 2

In [3]:
a=np.array([[2,2],[3,3]])
print(a)

[[1 2]
 [3 4]]
[[2 2]
 [3 3]]


2. Create a random numpy array of size 3 x 4

In [ ]:
b=np.random.rand(3,4)
print(b)

[[0.98520471 0.5732727  0.81175364 0.05385603]
 [0.02522851 0.80008391 0.1636756  0.18043337]
 [0.74286024 0.68956538 0.59970669 0.74279067]]


3. Create a numpy array of ones and a numpy array of zeroes

In [ ]:
c=np.ones((2,2))
d=np.zeros((2,2))

print("This is C")
print(c)
print("This is D")
print(d)

This is C
[[1. 1.]
 [1. 1.]]
This is D
[[0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [ ]:
e=np.random.rand(6,3)
print(e)

print("After transpose")
print(e.T)

[[0.17320918 0.7377369  0.95446616]
 [0.70130086 0.82945591 0.65041163]
 [0.01339554 0.73648143 0.15518542]
 [0.23107918 0.04154923 0.72504523]
 [0.1421227  0.15130996 0.17020669]
 [0.07663378 0.27255866 0.90679667]]
After transpose
[[0.17320918 0.70130086 0.01339554 0.23107918 0.1421227  0.07663378]
 [0.7377369  0.82945591 0.73648143 0.04154923 0.15130996 0.27255866]
 [0.95446616 0.65041163 0.15518542 0.72504523 0.17020669 0.90679667]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [ ]:
f=np.random.rand(3,2)
g=np.random.rand(2,1)

print("This is F")
print(f)
print("This is G")
print(g)

print("Dot product")
print(np.dot(f,g))

This is F
[[0.63694541 0.66227906]
 [0.74470997 0.93115838]
 [0.5530565  0.65526986]]
This is G
[[0.91321001]
 [0.49293517]]
Dot product
[[0.90812557]
 [1.13907732]
 [0.8280623 ]]
