In [1]:
import numpy as np

In [8]:
#Create a numpy array of size 2 x 2
a=np.array([[2,2],[3,3]])
print(a)

[[2 2]
 [3 3]]


In [9]:
#Create a random numpy array of size 3 x 4
b=np.random.rand(3,4)
print(b)

[[0.25180849 0.63154409 0.59019235 0.19914606]
 [0.01086341 0.48856022 0.63169059 0.16637382]
 [0.64113582 0.44799866 0.8505156  0.90347013]]


In [21]:
#Create a numpy array of ones and a numpy array of zeroes
c=np.ones((2,2))
d=np.zeros((2,2))

print("This is C")
print(c)
print("This is D")
print(d)

This is C
[[1. 1.]
 [1. 1.]]
This is D
[[0. 0.]
 [0. 0.]]


In [15]:
#Create a random numpy array of size 6x3 and transpose it
e=np.random.rand(6,3)
print(e)

print("After transpose")
print(e.T)

[[0.39154147 0.7823554  0.28812962]
 [0.514421   0.85955208 0.50556892]
 [0.91569956 0.97892412 0.33745158]
 [0.50637885 0.08291651 0.09443525]
 [0.71317279 0.28661425 0.33533612]
 [0.44815302 0.89514804 0.12294002]]
After transpose
[[0.39154147 0.514421   0.91569956 0.50637885 0.71317279 0.44815302]
 [0.7823554  0.85955208 0.97892412 0.08291651 0.28661425 0.89514804]
 [0.28812962 0.50556892 0.33745158 0.09443525 0.33533612 0.12294002]]


In [20]:
#Create two random numpy array of size n x p and p x m and then compute the dot product
f=np.random.rand(3,2)
g=np.random.rand(2,1)

print("This is F")
print(f)
print("This is G")
print(g)

print("Dot product")
print(np.dot(f,g))

This is F
[[0.15581799 0.69243453]
 [0.96298508 0.7728811 ]
 [0.14009651 0.80381901]]
This is G
[[0.37339337]
 [0.39534111]]
Dot product
[[0.33192924]
 [0.66512391]
 [0.37009381]]
